feat: issuer adapter oidc integration
trustbloc/sandbox pull request #892
Opened 2021-03-09 08:08 UTC by Moopli

- Issuer adapter requests login&consent for an access/refresh token that is scoped for a particular credential.
- Issuer adapter sends this token in an Authorization header with every   request for credential/assurance data.
- Issuer does not request login&consent, as the user ID, credential scope  information, and proof of consent are all determined by introspecting  the token sent by the issuer adapter.
- Issuer does not pre-fetch data from the CMS and cache it, instead performing the CMS lookup to service issuer-adapter requests as they come in.

Signed-off-by: Filip Burlacu <filip.burlacu@securekey.com>

2021-03-10 20:17 UTC, fqutishat approved these changes

2021-03-11 07:32 UTC, fqutishat requested changes

2021-03-11 07:32 UTC, fqutishat commented on test/bdd/fixtures/demo/.env
> +CSH_IMAGE_TAG=0.1.6
please revert this tags

2021-03-11 07:37 UTC, Moopli commented on test/bdd/fixtures/demo/.env
> +CSH_IMAGE_TAG=0.1.6
fixed

2021-03-11 13:05 UTC, fqutishat approved these changes

2021-03-11 13:18 UTC, rolsonquadras approved these changes

2021-03-11 13:19 UTC, merged